#
# ariston-remotethermo — Texinfo manual
#
# Copyright (C) 2026 Christian Brunello <brncrs@gmail.com>

info_TEXINFOS = stca-plugin-ariston-remotethermo.texi
stca_plugin_ariston_remotethermo_TEXINFOS = version.texi fdl.texi gpl.texi

AM_MAKEINFOFLAGS = -I $(srcdir)

EXTRA_DIST = stca-plugin-ariston-remotethermo.texi version.texi
